HW5
Illia1927/Mate_Fruit_Task pull request #1
Opened 2018-12-17 22:05 UTC by Illia1927

This is Home Work 5

2018-12-18 07:21 UTC, Gzyablik requested changes

2018-12-18 07:21 UTC, Gzyablik commented on src/main/java/HomeWork/HelpForFriend/Fruit.java
> +                        "\n|--------------------------");
While u want to display the fruit 2 times in a row, the next first line will be appended to the previous last

2018-12-18 07:21 UTC, Gzyablik commented on src/main/java/HomeWork/HelpForFriend/Test.java
> +        Date dateOne = Date.from(localDateOne.atStartOfDay(ZoneId.systemDefault()).toInstant());
Variable name should display what it do.

2018-12-18 07:21 UTC, Gzyablik commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +        try (PrintWriter printWriter = new PrintWriter(file)) {
Remember about DRY

2018-12-18 07:21 UTC, Gzyablik commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +        return dataBase.stream().filter((Fruit fruit) -> {
Use just fruit instead of Fruit fruit. Stream already knows about used type.

2018-12-18 07:21 UTC, Gzyablik commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +        return getSpoiledFruits(date).stream().filter(fruit -> variousFruitType == fruit.getVariousFruit()).collect(Collectors.toList());
Split the line by method calls.

2018-12-18 07:21 UTC, Gzyablik commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +        return dataBase.stream().filter(fruit -> !value.contains(fruit)).collect(Collectors.toList());
Split the line by method calls

2018-12-18 07:21 UTC, Gzyablik commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +        return getAvailableFruits(date).stream().filter(fruit -> variousFruitType == fruit.getVariousFruit()).collect(Collectors.toList());
Split the line by method calls

2018-12-21 19:06 UTC, BondarenkoJek commented on src/main/java/HomeWork/HelpForFriend/Fruit.java
> +
Remove a necessary line.

2018-12-21 19:07 UTC, BondarenkoJek commented on src/main/java/HomeWork/HelpForFriend/Fruit.java
> +
Remove unnecessary line.

2018-12-21 19:08 UTC, BondarenkoJek commented on src/main/java/HomeWork/HelpForFriend/Fruit.java
> +
Remove unnecessary line.

2018-12-21 19:09 UTC, BondarenkoJek commented on src/main/java/HomeWork/HelpForFriend/Fruit.java
> +
Remove unnecessary line.

2018-12-21 19:11 UTC, BondarenkoJek commented on src/main/java/HomeWork/HelpForFriend/Test.java
> +
Remove a man unnecessary line.

2018-12-21 19:11 UTC, BondarenkoJek commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +
Remove unnecessary line.

2018-12-21 19:17 UTC, BondarenkoJek commented on src/main/java/HomeWork/HelpForFriend/Fruit.java
> +    public void show() {
You have method “toString”

2019-01-03 12:53 UTC, boroda4436 requested changes

2019-01-03 12:53 UTC, boroda4436 commented on src/main/java/HomeWork/HelpForFriend/Test.java
> +        Date dateOne = Date.from(localDateOne.atStartOfDay(ZoneId.systemDefault()).toInstant());
@Illia1927 please fix it

2019-01-03 12:53 UTC, boroda4436 commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +        try (PrintWriter printWriter = new PrintWriter(file)) {
@Illia1927

2019-01-03 12:53 UTC, boroda4436 commented on src/main/java/HomeWork/HelpForFriend/TradeShop.java
> +            return calendar.getTime().getTime() < date.getTime();
@Illia1927 this block of code is not elegant. Move it to separate method and then use it is stream

2019-01-12 12:58 UTC, boroda4436 approved these changes
LGTM

2019-01-21 23:48 UTC, merged